[package]
name = "bls-signatures-rs"
version = "0.1.0"
authors = ["Mario Cao <mariocao@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
failure = "0.1.5"
bn = { git = "https://github.com/paritytech/bn", default-features = false }
rustc-hex = "1.0"
serde_json = "1.0.39"
hex = "0.3.2"

[dev-dependencies]
