[package]
name = "bls-signatures-rs"
version = "0.1.0"
description = "Open source implementation of Bonneh-Lynn-Shacham (BLS) signatures written in Rust"
keywords = ["bls", "Bonneh-Lynn-Shacham", "bn256"]
categories = ["algorithms", "cryptography"]
authors = ["Witnet Foundation <info@witnet.foundation>"]
license = "MIT"
edition = "2018"
homepage = "https://github.com/witnet/bls-signatures-rs"
documentation = "https://docs.rs/bls-signatures-rs/"
repository = "https://github.com/witnet/bls-signatures-rs"
readme = "README.md"
exclude = ["/.travis.yml"]

[dependencies]
bn = { git = "https://github.com/paritytech/bn", rev = "635c4cdd560bc0c8b262e6bf809dc709da8bcd7e", default-features = false}
byteorder = "1.3.4"
digest = "0.8.1"
failure = "0.1.8"
hex = "0.4.2"
rustc-hex = "2.1.0"
serde_json = "1.0.52"
sha2 = "0.8.1"

[dev-dependencies]
