[package]
name = "bls-signatures-rs"
version = "0.1.0"
authors = ["Mario Cao <mariocao@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bn = { git = "https://github.com/paritytech/bn", rev = "635c4cdd560bc0c8b262e6bf809dc709da8bcd7e", default-features = false}
byteorder = "1.3.4"
digest = "0.8.1"
failure = "0.1.8"
hex = "0.4.2"
rustc-hex = "2.1.0"
serde_json = "1.0.52"
sha2 = "0.8.1"

[dev-dependencies]
